name: CI CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [manual-action-trigger]

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        if: success()
        run: npm run lint

      - name: Run Unit Tests
        if: success()
        run: npm run test

      - name: Run Build
        if: success()
        run: npm run build
         env:
          NODE_ENV: production
          PUBLIC_URL: https://theadeel.com
          REACT_APP_GH_TOKEN: ${{ secrets.REACT_APP_GH_TOKEN }}


      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: build.artifact
          path: build